name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login
        run: docker login ghcr.io -u ggos3 --password-stdin ${{secrets.PASSWORD}

      - name: build
        run: docker build .

      - name: push
        run: docker push ghrc.io/ggos3/test:latest
