name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        id : docker_build
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghrc.io/${{ github.repository_owner }}/test:latest

      - name: build
        run: docker build .

      - name: push
        run: docker push ghrc.io/ggos3/test:latest

