name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login
        run: \
          token = ${{ secrets.PASSWORD }} \
          echo $token | docker login ghcr.io -u ggos3 password-stdin

      - name: build
        run: docker build .

      - name: push
        run: docker push ghrc.io/ggos3/test:latest
